"""Add credit_packages table

Revision ID: 6f360e927f5e
Revises: 75042bb50ab1
Create Date: 2025-07-08 21:57:53.918765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f360e927f5e'
down_revision: Union[str, None] = '75042bb50ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_id', sa.String(), nullable=False),
    sa.Column('credits_amount', sa.Integer(), nullable=False),
    sa.Column('price_display', sa.String(), nullable=True),
    sa.Column('is_popular', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_packages_id'), 'credit_packages', ['id'], unique=False)
    op.create_index(op.f('ix_credit_packages_name'), 'credit_packages', ['name'], unique=False)
    op.create_index(op.f('ix_credit_packages_price_id'), 'credit_packages', ['price_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_packages_price_id'), table_name='credit_packages')
    op.drop_index(op.f('ix_credit_packages_name'), table_name='credit_packages')
    op.drop_index(op.f('ix_credit_packages_id'), table_name='credit_packages')
    op.drop_table('credit_packages')
    # ### end Alembic commands ###
