import { NextPage, GetStaticProps } from 'next';
import { useQuery } from '@tanstack/react-query';
import Image from 'next/image';
import Layout from '@/components/Layout';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import ImageGrid from '@/components/ImageGrid';
import ShareModal from '@/components/ShareModal';
import { useState } from 'react';
import { CommunityImage as CommunityImageType } from '@/types';
import { useSession } from 'next-auth/react';

const CommunityPage: NextPage = () => {
  const { t } = useTranslation('common');
  const [selectedImage, setSelectedImage] = useState<CommunityImageType | null>(null);
  const { data: session } = useSession();

  const { data: images, isLoading, error } = useQuery<CommunityImageType[]>({
    queryKey: ['community-images'],
    queryFn: () => fetch('/api/community/images').then(res => res.json()),
  });

  const handleFavorite = (id: number, favorited: boolean) => {
    // Placeholder for favorite logic
    console.log('Favourited:', id, favorited);
  };

  return (
    <div className="bg-stone-900 min-h-screen">
      <div className="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
        <div className="text-center">
          <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">{t('community_gallery', 'Community Gallery')}</h2>
          <p className="mt-4 text-lg leading-8 text-stone-400">
            {t('community_description', 'Explore amazing images generated by the community.')}
          </p>
        </div>

        {isLoading && <p className="text-center text-white mt-8">Loading...</p>}
        {error && <p className="text-center text-red-500 mt-8">Error loading images.</p>}
        
        {images && <ImageGrid images={images} onShare={setSelectedImage} onFavorite={handleFavorite} isAuthenticated={!!session} />}

        {selectedImage && (
          <ShareModal 
            image={selectedImage}
            isOpen={!!selectedImage}
            onClose={() => setSelectedImage(null)}
          />
        )}
      </div>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? 'en', ['common'])),
    },
  };
};

export default CommunityPage; 